/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package intergraf;

import gerTarefas.GerenciadorInterGraf;
import java.awt.Color;
import java.text.ParseException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Bebida;
import modelo.Cliente;
import modelo.Pastel;

/**
 *
 * @author mathe
 */
public class DlgCadPedido extends javax.swing.JDialog {
    
    private Cliente cliSelecionado;
    private GerenciadorInterGraf gerIG;
    
    public DlgCadPedido(java.awt.Frame parent, boolean modal, GerenciadorInterGraf gerIG) {
        super(parent, modal);
        initComponents();
        this.gerIG = gerIG;
        this.cliSelecionado = null;
        
    }
    
    private boolean validar(String nome) {
        String msgErro = "";
        lblNome.setForeground(Color.black);
        lblPastel.setForeground(Color.black);

        if (nome.isEmpty()) {
            msgErro = msgErro + "Nome inválido!\n";
            lblNome.setForeground(Color.red);
        }

        if (msgErro.isEmpty()) {
            return true;
        } else {

            JOptionPane.showMessageDialog(this, msgErro, "Erro cadastro PEDIDO", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    private void adicionarTabela(Pastel pastel, Bebida bebida) {
        
        ((DefaultTableModel) tblPedido.getModel()).addRow(new Object[3]);

        int linha = tblPedido.getRowCount() - 1;
        int col = 0;
        tblPedido.setValueAt(pastel, linha, col++);
        tblPedido.setValueAt(bebida, linha, col++);
        tblPedido.setValueAt(pastel.getValor()+bebida.getValorbeb(), linha, col++);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCadPedido = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblPastel = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        cmbPasteis = new javax.swing.JComboBox<>();
        btnPesqCli = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedido = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        cmbBebidas = new javax.swing.JComboBox<>();
        lblPastel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        lblCadPedido.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblCadPedido.setForeground(new java.awt.Color(255, 102, 51));
        lblCadPedido.setText("Cadastro de Pedido");

        lblNome.setText("Nome");

        lblPastel.setText("Pastel");

        cmbPasteis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPasteisActionPerformed(evt);
            }
        });

        btnPesqCli.setText("Pesquisar Cliente");
        btnPesqCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqCliActionPerformed(evt);
            }
        });

        btnAdicionar.setText("Adicionar ao Pedido");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        tblPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pastel", "Bebida", "Valor"
            }
        ));
        jScrollPane1.setViewportView(tblPedido);

        lblTotal.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lblTotal.setText("Total");

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        cmbBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBebidasActionPerformed(evt);
            }
        });

        lblPastel1.setText("Bebida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCadPedido)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPastel)
                                .addGap(23, 23, 23)
                                .addComponent(cmbPasteis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addGap(18, 18, 18)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesqCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPastel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmbBebidas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAdicionar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadPedido)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesqCli))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPasteis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPastel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPastel1))
                .addGap(18, 18, 18)
                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPasteisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPasteisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPasteisActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        
        String nome = txtNome.getText();
        Pastel pastel = (Pastel) cmbPasteis.getSelectedItem();
        Bebida bebida = (Bebida) cmbBebidas.getSelectedItem();
        
        
        if (validar(nome)) {
            adicionarTabela(pastel, bebida);
        }
        
        cmbPasteis.setSelectedIndex(11);
        cmbBebidas.setSelectedIndex(21);
        
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void cmbBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBebidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBebidasActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        gerIG.carregarCombo(cmbPasteis, Pastel.class);
        gerIG.carregarCombo(cmbBebidas, Bebida.class);
        
        cmbPasteis.setSelectedIndex(11);
        cmbBebidas.setSelectedIndex(21);
    }//GEN-LAST:event_formComponentShown

    private void btnPesqCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqCliActionPerformed
        cliSelecionado = gerIG.abrirPesqCliente();
        txtNome.setText(cliSelecionado.getNome());
    }//GEN-LAST:event_btnPesqCliActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnPesqCli;
    private javax.swing.JComboBox<String> cmbBebidas;
    private javax.swing.JComboBox<String> cmbPasteis;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCadPedido;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPastel;
    private javax.swing.JLabel lblPastel1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblPedido;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
