/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package intergraf;

import gerTarefas.FuncoesUteis;
import gerTarefas.GerenciadorInterGraf;
import java.awt.Color;
import java.text.ParseException;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Cliente;
import org.hibernate.HibernateException;

/**
 *
 * @author mathe
 */
public class DlgCadCliente extends javax.swing.JDialog {

   private GerenciadorInterGraf gerIG;
   private Cliente cliSelecionado;
   
    public DlgCadCliente(java.awt.Frame parent, boolean modal, GerenciadorInterGraf gerIG ) {
        super(parent, modal);
        initComponents();
        this.gerIG = gerIG;
        cliSelecionado = null;
        habilitarBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpSexo = new javax.swing.ButtonGroup();
        lblCadCliente = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblDtNasc = new javax.swing.JLabel();
        lblRua = new javax.swing.JLabel();
        lblNum = new javax.swing.JLabel();
        lblComplem = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblRef = new javax.swing.JLabel();
        lblFixo = new javax.swing.JLabel();
        lblCel = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        txtNum = new javax.swing.JTextField();
        txtComplemento = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtRef = new javax.swing.JTextField();
        txtFixo = new javax.swing.JTextField();
        txtCel = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        txtData = new javax.swing.JFormattedTextField();
        pnSexo = new javax.swing.JPanel();
        lblSexo = new javax.swing.JLabel();
        rdbMasc = new javax.swing.JRadioButton();
        rdbFemin = new javax.swing.JRadioButton();
        btnAlterar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCadCliente.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblCadCliente.setForeground(new java.awt.Color(255, 102, 51));
        lblCadCliente.setText("Cadastro de Cliente");

        lblNome.setText("Nome");

        lblCpf.setText("CPF");

        lblDtNasc.setText("Nascimento");

        lblRua.setText("Rua");

        lblNum.setText("Num");

        lblComplem.setText("Complemento");

        lblBairro.setText("Bairro");

        lblRef.setText("Referencia");

        lblFixo.setText("Tel Fixo");

        lblCel.setText("Celular");

        lblEmail.setText("E-mail");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCpfFocusLost(evt);
            }
        });

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        pnSexo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSexo.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lblSexo.setText("Sexo");

        grpSexo.add(rdbMasc);
        rdbMasc.setMnemonic('M');
        rdbMasc.setText("Masculino");
        rdbMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMascActionPerformed(evt);
            }
        });

        grpSexo.add(rdbFemin);
        rdbFemin.setMnemonic('F');
        rdbFemin.setText("Feminino");

        javax.swing.GroupLayout pnSexoLayout = new javax.swing.GroupLayout(pnSexo);
        pnSexo.setLayout(pnSexoLayout);
        pnSexoLayout.setHorizontalGroup(
            pnSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSexoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSexo)
                    .addComponent(rdbMasc)
                    .addComponent(rdbFemin))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        pnSexoLayout.setVerticalGroup(
            pnSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSexoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSexo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbMasc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdbFemin)
                .addContainerGap())
        );

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar Campos");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCadCliente)
                            .addComponent(lblEmail)
                            .addComponent(lblFixo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDtNasc)
                                    .addComponent(lblRua)
                                    .addComponent(lblNum)
                                    .addComponent(lblBairro)
                                    .addComponent(lblRef))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmail)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCel, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtNum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblComplem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtBairro)
                                    .addComponent(txtRef)
                                    .addComponent(txtRua)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome)
                                    .addComponent(lblCpf))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addComponent(pnSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCpf)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDtNasc)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pnSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRua)
                            .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblComplem)
                                .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblBairro))
                    .addComponent(txtBairro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRef))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFixo)
                    .addComponent(txtFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCel)
                    .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnNovo)
                    .addComponent(btnLimpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfFocusLost

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
            cliSelecionado = gerIG.abrirPesqCliente();
            preencherCampos(cliSelecionado);
            habilitarBotoes();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao selecionar o cliente", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void rdbMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbMascActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        String nome = txtNome.getText();
        String cpf = txtCpf.getText();
        String txtDtNasc = txtData.getText();
        char sexo = (char) grpSexo.getSelection().getMnemonic();
        String rua = txtRua.getText();
        String txtNumero = txtNum.getText();
        String complemento = txtComplemento.getText();
        String bairro = txtBairro.getText();
        String referencia = txtRef.getText();
        String telFixo = txtFixo.getText();
        String celular = txtCel.getText();
        String email = txtEmail.getText();

        if (validarCampos()) {
            try {
                if (cliSelecionado == null) {
                    int id = gerIG.getGerDominio().inserirCliente(nome, cpf, FuncoesUteis.strToDate(txtDtNasc), sexo,
                            rua, Integer.parseInt(txtNumero), complemento, bairro, referencia, telFixo, celular, email);
                    JOptionPane.showMessageDialog(this, "Cliente " + id + " inserido com sucesso");
                } else {
                    gerIG.getGerDominio().alterarCliente(cliSelecionado, nome, cpf, FuncoesUteis.strToDate(txtDtNasc), sexo,
                            rua, Integer.parseInt(txtNumero), complemento, bairro, referencia, telFixo, celular, email);
                    JOptionPane.showMessageDialog(this, "Cliente " + cliSelecionado.getIdCliente() + " alterado com sucesso");
                }

            } catch (HibernateException ex) {
                JOptionPane.showMessageDialog(this, "ERRO ao inserir cliente. " + ex, "ERRO Cliente", JOptionPane.ERROR_MESSAGE);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "ERRO na data.", "ERRO Cliente", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        limparCampos();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        String nome = txtNome.getText();
        String cpf = txtCpf.getText();
        String txtDtNasc = txtData.getText();
        char sexo = (char) grpSexo.getSelection().getMnemonic();
        String rua = txtRua.getText();
        String txtNumero = txtNum.getText();
        String complemento = txtComplemento.getText();
        String bairro = txtBairro.getText();
        String referencia = txtRef.getText();
        String telFixo = txtFixo.getText();
        String celular = txtCel.getText();
        String email = txtEmail.getText();

        if (validarCampos()) {
            try {
                if (cliSelecionado == null) {
                    int id = gerIG.getGerDominio().inserirCliente(nome, cpf, FuncoesUteis.strToDate(txtDtNasc), sexo,
                            rua, Integer.parseInt(txtNumero), complemento, bairro, referencia, telFixo, celular, email);
                    JOptionPane.showMessageDialog(this, "Cliente " + id + " inserido com sucesso");
                } else {
                    gerIG.getGerDominio().alterarCliente(cliSelecionado, nome, cpf, FuncoesUteis.strToDate(txtDtNasc), sexo,
                            rua, Integer.parseInt(txtNumero), complemento, bairro, referencia, telFixo, celular, email);
                    JOptionPane.showMessageDialog(this, "Cliente " + cliSelecionado.getIdCliente() + " alterado com sucesso");
                }

            } catch (HibernateException ex) {
                JOptionPane.showMessageDialog(this, "ERRO ao alterar cliente. " + ex, "ERRO Cliente", JOptionPane.ERROR_MESSAGE);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "ERRO na data.", "ERRO Cliente", JOptionPane.ERROR_MESSAGE);
            }

        }   
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed
    
    private void habilitarBotoes() {
        if (cliSelecionado == null) {
            btnNovo.setVisible(true);
            btnAlterar.setVisible(false);
        } else {
            btnNovo.setVisible(false);
            btnAlterar.setVisible(true);
        }
    }
    
    private void preencherCampos(Cliente cli) throws ParseException {
        if (cli != null) {
            txtNome.setText(cli.getNome());
            txtCpf.setText(cli.getCpf());
            txtData.setText(cli.getDataFormatada());
            txtRua.setText(cli.getRua());
            txtNum.setText(String.valueOf(cli.getNumero()));
            txtComplemento.setText(cli.getComplemento());
            txtBairro.setText(cli.getBairro());
            txtRef.setText(cli.getReferencia());
            txtFixo.setText(cli.getTelFixo());
            txtCel.setText(cli.getCelular());
            txtEmail.setText(cli.getEmail());

            if (cli.getSexo() == 'M') {
                rdbMasc.setSelected(true);
            } else {
                rdbFemin.setSelected(true);
            }
        }
    }
    
    private boolean validarCampos() {

        String msgErro = "";

        lblNome.setForeground(Color.black);
        lblNum.setForeground(Color.black);
        lblCpf.setForeground(Color.black);
        lblDtNasc.setForeground(Color.black);

        if (txtNome.getText().isEmpty()) {
            msgErro = msgErro + "Digite seu nome.\n";
            lblNome.setForeground(Color.red);
        }

        if (FuncoesUteis.isCPF(txtCpf.getText()) == false) {
            msgErro = msgErro + "CPF inválido.\n";
            lblCpf.setForeground(Color.red);
        }
        
        try {
            int num = Integer.parseInt(txtNum.getText());
            Date dtNasc = FuncoesUteis.strToDate(txtData.getText());
        } catch (NumberFormatException erro) {
            msgErro = msgErro + "Número inválido.\n";
            lblNum.setForeground(Color.red);
        } catch (ParseException ex) {
            msgErro = msgErro + "Data inválida.\n";
            lblDtNasc.setForeground(Color.red);
        } catch (Exception erro) {
            msgErro = msgErro + erro.getMessage() + "\n";
            lblNum.setForeground(Color.red);
        }

        // COLOCAR VALIDAÇÃO DOS OUTROS CAMPOS
        if (msgErro.isEmpty()) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, msgErro, "ERRO Cliente", JOptionPane.ERROR_MESSAGE);
            return false;
        }

    }
    
    private void limparCampos() {
        cliSelecionado = null;
        txtNome.setText("");
        txtCpf.setText("");
        txtData.setText("");
        txtRua.setText("");
        txtNum.setText("");
        txtComplemento.setText("");
        txtBairro.setText("");
        txtRef.setText("");
        txtFixo.setText("");
        txtCel.setText("");
        txtEmail.setText("");
        habilitarBotoes();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.ButtonGroup grpSexo;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCadCliente;
    private javax.swing.JLabel lblCel;
    private javax.swing.JLabel lblComplem;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDtNasc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFixo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblRef;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JPanel pnSexo;
    private javax.swing.JRadioButton rdbFemin;
    private javax.swing.JRadioButton rdbMasc;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCel;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFixo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtRef;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables
}
