/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package intergraf;

import gerTarefas.GerenciadorInterGraf;

/**
 *
 * @author mathe
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private GerenciadorInterGraf gerIG;
    
    public FrmPrincipal(GerenciadorInterGraf novoGerIG) {        
        initComponents();
        gerIG = novoGerIG;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCadastro = new javax.swing.JMenu();
        mnuCadPedido = new javax.swing.JMenuItem();
        mnuCadCliente = new javax.swing.JMenuItem();
        mnuConsultas = new javax.swing.JMenu();
        mnuPesqCliente = new javax.swing.JMenuItem();
        mnuPesqPedido = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/Logotipo Nome Monograma Minimalista Preto e Branco.png"))); // NOI18N

        mnuCadastro.setText("Cadastro");

        mnuCadPedido.setText("Cadastrar Pedido");
        mnuCadPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadPedidoActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCadPedido);

        mnuCadCliente.setText("Cadastrar Cliente");
        mnuCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadClienteActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCadCliente);

        jMenuBar1.add(mnuCadastro);

        mnuConsultas.setText("Consultas");

        mnuPesqCliente.setText("Pesquisar Cliente");
        mnuPesqCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPesqClienteActionPerformed(evt);
            }
        });
        mnuConsultas.add(mnuPesqCliente);

        mnuPesqPedido.setText("Pesquisar Pedido");
        mnuPesqPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPesqPedidoActionPerformed(evt);
            }
        });
        mnuConsultas.add(mnuPesqPedido);

        jMenuBar1.add(mnuConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCadPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadPedidoActionPerformed
        gerIG.abrirCadPedido();
    }//GEN-LAST:event_mnuCadPedidoActionPerformed

    private void mnuCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadClienteActionPerformed
        gerIG.abrirCadCliente();
    }//GEN-LAST:event_mnuCadClienteActionPerformed

    private void mnuPesqClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPesqClienteActionPerformed
        gerIG.abrirPesqCliente();
    }//GEN-LAST:event_mnuPesqClienteActionPerformed

    private void mnuPesqPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPesqPedidoActionPerformed
        gerIG.abrirPesqPedido();
    }//GEN-LAST:event_mnuPesqPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuCadCliente;
    private javax.swing.JMenuItem mnuCadPedido;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenu mnuConsultas;
    private javax.swing.JMenuItem mnuPesqCliente;
    private javax.swing.JMenuItem mnuPesqPedido;
    // End of variables declaration//GEN-END:variables
}
